version: ~> 1.0

os: linux

services:
  - docker

language: shell

script:
  - export VERSION="$(date "+%Y-%m-%d")-${TRAVIS_BUILD_NUMBER}"
  - docker build -t "heapy/bsuir-diploma-latex:${VERSION}" -t latest ./docker

deploy:
  provider: script
  script: bash devops/deploy.sh
  on:
    branch: master
