version: ~> 1.0

os: linux

services:
  - docker

language: shell

script:
  - export PACKAGE_VERSION="$(date "+%Y-%m-%d")"
  - echo "${PACKAGE_VERSION}"
  - docker build -t "heapy/bsuir-diploma-latex:${PACKAGE_VERSION}-${TRAVIS_BUILD_NUMBER}" -t latest ./

deploy:
  provider: script
  script: bash devops/deploy.sh
  on:
    branch: master
