version: ~> 1.0

os: linux

services:
  - docker

language: shell

script:
  - export VERSION="$(date "+%Y%m%d")-${TRAVIS_BUILD_NUMBER}"
  - echo "Docker tag - ${VERSION}"
  - docker build -t "heapy/bsuir-diploma-latex:${VERSION}" -t latest ./.ci

deploy:
  provider: script
  script: bash ./.ci/deploy.sh
  on:
    branch: master

# docker build .ci -t bdl
# docker run -it --rm -v src:/home/workdir -t bdl
