version: ~> 1.0

os: linux

services:
  - docker

language: shell

before_install:
  - echo "Europe/Minsk" | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  - export VERSION="$(date "+%Y-%m-%d")-${TRAVIS_BUILD_NUMBER}"
  - docker build -t "heapy/bsuir-diploma-latex:${VERSION}" -t latest ./

deploy:
  provider: script
  script: bash devops/deploy.sh
  on:
    branch: master
